"""transaction tables schema v2

Revision ID: 2720c783f85c
Revises: e49ce8e4fe81
Create Date: 2021-10-16 22:30:38.805643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2720c783f85c'
down_revision = 'e49ce8e4fe81'
branch_labels = None
depends_on = None

# TODO: add table creation logic here, not sure why auto-generation doesn't work for table creation
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
