"""Added a new field count

Revision ID: e2bda7310205
Revises: 2e072dece469
Create Date: 2021-10-15 00:34:25.300969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2bda7310205'
down_revision = '2e072dece469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_position', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_position', 'count')
    # ### end Alembic commands ###
